### ISSUE TITLE
Research ingest ordering issue for parent collections.

### ISSUE THREAD

**Issue by sharkinsspatial** [sat-utils/sat-api#172]

**Comment by matthewhanson** [comment]
We talked about this and decided that for now it's fine to explicitly state in the README instructions for data ingestion that collections should be ingested first (as a separate step), before ingesting any items that belong to the collection.

Adding this to 0.2.4, update README to reflect this.

**Comment by matthewhanson** [comment]
The README for ingesting is actually in sat-api-deployment (because it's particular to the ingest lambda on AWS), so should be handled there.

The API and Ingest Lambdas really should be in the deployment repo anyway, as they are very specific to AWS, and are the most likely thing that users may want to override by providing changes to the handlers.  This would make this repo just a generic STAC compliant API library with pluggable backends (and you would combine backend  + API in your handler or other entrypoint).
