### ISSUE TITLE
Pre-collection LS8 in AWS with distinct archive version from what is being indexed (live version API)

### ISSUE THREAD

**Issue by fredliporace** [sat-utils/sat-api#18]
It seems that the results being returned from some Pre-collection LS8 in AWS is using an archive version which is not available (yet?) in AWS.

Take for instance this query:
https://api.developmentseed.org/satellites/?satellite_name=landsat-8&limit=1&path=217&row=076&acquisitionDate=2016-01-15

The AWS- related returned data indicates an archive version 02, for instance:
http://landsat-pds.s3.amazonaws.com/L8/217/076/LC82170762016015LGN02/LC82170762016015LGN02_thumb_large.jpg

The above file is not available. If I manually change to use archive version 00 it works:
http://landsat-pds.s3.amazonaws.com/L8/217/076/LC82170762016015LGN00/LC82170762016015LGN00_thumb_large.jpg

The "Landsat on AWS" browse shows only archive version 00 for the selected scene:
https://landsatonaws.com/L8/217/076/

**Comment by drewbo** [comment]
Thanks for the feedback @fredliporace; we noticed this one too and have heard that AWS doesn't plan to re-ingest the pre-collection 1 data so we might need to make a manual string replacement change in the update scripts. Happy for other solutions as well if you have other ideas

**Comment by fredliporace** [comment]
Thanks for the update @drewbo.

It's bad that AWS does not plan to re-ingest pre-collection 1 data, AFAIK newer archive versions may have better radiometric/geometric quality than older archive since they are reprocessed with updated calibration parameters. Does the same problem happen with your index to Google repository?

Regarding suggestions what I'm doing on the client side now is to check the availability of the archive version by downloading the 'aws_index' key, trying which archive versions from 0 up to the archive version sat-api returns, and updating the key for my processing (I may post the Python code if someone reading this think it might be useful).

On the server side I don't have lambda fluency to quickly check your code for what you are using as the source for the index, will do that later. I found that AWS index contains the archive that is being hosted in AWS.

https://landsat-pds.s3.amazonaws.com/scene_list.gz

**Comment by fredliporace** [comment]
This is from landsat-pds list (edited to remove names and e-mails). It seems that AWS has plans to replace pre-colletion with collection 1 data, although there is no timeline.

<pre>
Date: Fri, 21 Jul 2017 16:19:20 +0000

**Comment by matthewhanson** [comment]
The pre-collection Landsat data might still be replaced in the future, but in the meantime we've developed some work-arounds.

First, I think it's worth going over what Collection 1 data means. Collection 1 data is really. The explicit list of changes are given here: https://landsat.usgs.gov/landsat-collections#additional_data_changes_applied_during_reprocessing

As can be seen, there should be no radiometric differences, with the exception of *Landsat 8 TIRS*. The main changes moving to Collection 1 are:
- new cloud cover algorithm
- some filename changes
- metadata additions
- assignment of a processing level (no change to processing, just assigned a designation of quality)

Also note that the scene ID naming convention for collection 1 has not changed. Scene IDs for new scenes will look the same as old scenes. However, collection 1 did add a Product identifier, which is like the scene ID but indicates processing level. It can be therefore inferred therefore that multiple products can be part of a single ID (most commonly a real time product + a final product).  

Scene IDs indicate a *revision number*. New revisions were created for older data to add in the changes given above to make them Collection 1.  "Collection 1" doesn't mean newer data, or some date at which data was switched over...Collection 1 is simply a *processing level*, so all legacy data can be processed into Collection 1 data.

sat-api still uses Scene IDs, even for C1 data, it's just that the revision number is one higher. For the AWS data there is no way to determine if the data is pre-collection or C1, without looking at the metadata or files available (see above).  For data prior to May 1, 2016 on AWS the old data was not updated to the new C1 format. (i.e. missing metadata, missing files, and a TIRS band that was calibrated slightly differently).  I'm currently working on a new sat-api that adjusts for the possibility of older revisions of the data rather than the latest. This is simply a work-around for the fact that AWS is not the original version of the data, it is a copy that can be out of sync.

What this means is that a new version of sat-api won't be plagued by bad links, but still cannot guarantee that the data in the API is the latest version.

cc @drewbo @scisco

**Comment by matthewhanson** [comment]
The older landsat data on AWS is still pre-collection 1, which means the version numbers are out of sync as described above.

Release 0.3.0 solves this by providing links to the latest revision of the data that is present on AWS, rather than the same revision that is reported in the Landsat flat file catalog.
