### ISSUE TITLE
Landsat question

### ISSUE THREAD

**Issue by purepear** [sat-utils/sat-api#42]
I see that you are getting the list from https://landsat.usgs.gov/landsat/metadata_service/bulk_metadata_files/LANDSAT_8_C1.csv (btw they have gzipped version of it https://landsat.usgs.gov/landsat/metadata_service/bulk_metadata_files/LANDSAT_8_C1.csv.gz)

I believe you do this because it contains  polygon coordinates rather than only bbox(min_lat, min_lon, max_lat, max_lon) from AWS and Google. And it contains Pre-Collection and C1 together as bonus. 

My question is: 
Is it possible to get the list from AWS and project bbox to polygon? Like you do for Sentinel.

Because i ran some tests and there are broken AWS links. And since my idea is to use AWS so that i don't have to download scenes.. I'm wondering if using the AWS list with projection for polygons is possible.. because then i can do correct AOI spatial queries on polygons rather than bbox

I've been researching for a week now and things are all over the place with lists and data :)

Thank you for you work... just wondering if this is possible :)

* by polygons i mean (lat,lon) for each of the 4 points of the scene

**Comment by matthewhanson** [comment]
hi @purepear ,

the issue with using just the bounding box is that its then represents the entire Landsat scene, not the area within that scene that actually contains data.   The 'data_geometry' is the polygon that covers the data area within the file, so this is what you want when searching for scenes.

When you say broken links, do you mean in the file or in sat-api?  There are indeed broken links due to the fact that USGS incremented the revision of all scenes after C1 was released, but the data was not updated on AWS, so older scenes are all older revisions.

However, this has been fixed in the current deployed version of sat-api. When I ingest the data I check for the existence of the file and if it's missing I'll check older revisions. So there should not be broken links in the returned links from sat-api.

An alternate approach to using the list file, and this may be what you are getting at, is to crawl the bucket and ingest the metadata directly from the MTL file.  This may be a better approach, but would certainly take longer time to process.  And right now I'm working on the new version of sat-api which uses the [STAC](https://github.com/radiantearth/stac-spec/tree/dev) spec, and the idea is there will be a flat catalog for Landsat data on AWS which will make these problems moot.

**Comment by purepear** [comment]
Hi @matthewhanson ,

thanks you for the detailed answer  

and yes :) ... that's exactly my problem with bbox and that's why i think USGS csv list it better than Amazon's because it provides the polygon coords of the actual image rather then just bbox(min_lat, min_lon, max_lat, max_lon).. In my mind the ideal scenario would be to use AWS list and get the polygon of the actual image with some sort of projection function. Looks like Landsat data is always skewed with a similar angle.. but i'm new to this game so i'm not sure how geo curvature and other factors play in this equation. Do you know if it's possible to get the polygon from AWS csv(bbox) alone? I believe you're doing sth similar for Sentinel https://github.com/sat-utils/sat-api/blob/2c73705d128bdbc0f5a5e7c9f894e1fb2f4f4edd/lambdas/sentinel/index.js#L71

About the broken links... here's an example AOI query of Sydney https://api.developmentseed.org/satellites/?limit=1000&satellite_name=landsat-8&cloud_to=20&date_to=2017-09-01&intersects=%7B%22type%22%3A%22Polygon%22%2C%22coordinates%22%3A%5B%5B%5B151.053611019071%2C-33.7891612825314%5D%2C%5B151.053611019071%2C-34.0097231342993%5D%2C%5B151.309043147944%2C-34.0097231342993%5D%2C%5B151.309043147944%2C-33.7891612825314%5D%2C%5B151.053611019071%2C-33.7891612825314%5D%5D%5D%7D 

the first scene AWS links are broken: https://landsat-pds.s3.amazonaws.com/c1/L8/090/084/LC08_L1TP_090084_20170819_20180203_01_T1/LC08_L1TP_090084_20170819_20180203_01_T1_ANG.txt

About the STAC spec: Is this sth that AWS will provide instead of the csv list? Or is it what sat-api will provide, collecting it from AWS/USGS/Google csv lists? I see it's JSON which means it'll be twice the size of current csv files

**Comment by matthewhanson** [comment]
We are taking a new approach now, where first we will be creating a STAC flat file catalog for data sources (this will happen in another repo entirely). Then sat-api will ingest the flat file catalogs and not deal with CSV files at all.
