### ISSUE TITLE
Make HTML endpoints for nicer navigation of the service

### ISSUE THREAD

**Issue by cholmes** [sat-utils/sat-api#48]
One of the nicest things about WFS3 is how html is a top level citizen. See like http://geo.weather.gc.ca/geomet-beta/features/?f=html

It'd be nice to do the same with sat-api. The core navigation should be relatively easy, and would be a big win. It'd mostly just be f=html or page.html type links for each of the endpoints.

The other bit is the actual items, which are more challenging. But could hopefully make use of https://github.com/radiantearth/stac-browser code in some way - use the same JS code to generate just the 'page' like http://planet-stac.netlify.com/item/hurricane-harvey/0831/20170831_195552_SS02 from the json.

**Comment by matthewhanson** [comment]
STAC Browser can be used to browse a STAC dynamic API now, so I think that it makes sense to have that be a separate browser that can point to the API rather than building in an HTML display option.

I'm closing this for now.  If HTML gets added to the STAC spec then we can figure out how to implement in sat-api, but right now I'd like to focus on keeping up to date with STAC rather than adding new features.
