### ISSUE TITLE
Collection filter is not working

### ISSUE THREAD

**Issue by purepear** [sat-utils/sat-api#50]
Both return the same results

https://sat-api.developmentseed.org/search/stac?datetime=2017-08&collection=landsat-8

https://sat-api.developmentseed.org/search/stac?datetime=2017-08&collection=sentinel-2

**Comment by matthewhanson** [comment]
hi @purepear Sorry I do need to update the documentation, but I've just deployed a new version.

Two things, the collection names have changed and also you need to search on the "c:id" field rather than "collection".

See list of all collections with:
https://sat-api.developmentseed.org/collections

You can search items within a collection with, e.g.,
https://sat-api.developmentseed.org/collections/landsat-8-l1/items

Or cross-collection searches with
https://sat-api.developmentseed.org/search/stac

And you can also search using the c:id field if you wish:
https://sat-api.developmentseed.org/search/stac?c:id=landsat-8-l1
